# 小部屋テンプレート
# テスト用のシンプルなチャンク

[[chunk]]
  name     = "small_room"
  palettes = ["standard"]
  size     = [10, 10]
  weight   = 100

  map = """
####..####
#........#
#........#
#..CTC...#
#........#
#........#
#........#
#........#
#X..B....#
##########
"""
