# 小部屋テンプレート
# テスト用のシンプルな施設

[[facility]]
  name     = "小部屋"
  palettes = ["standard"]
  size     = [10, 10]
  type     = "small_room"
  weight   = 100

  map = """
##########
#........#
#..T..C..#
#..T..C..#
#........#
#..S..X..#
#..S..X..#
#........#
#........#
##########
"""
