# NPC広場チャンク
# 町の中央に配置する20x20の広場
# 中央に焚き火、周囲にランタンを配置

[[chunk]]
  name     = "20x20_town_plaza"
  palettes = ["standard", "town"]
  weight   = 1

  map = """
##......rrr.......##
#rrr....rrr.....rrr#
#rrr....rrr.....rrr#
#rrL....rrr.....Lrr#
#.......rrr........#
#..$...rrrrr.......#
#.....rrrrrrr...3..#
#....rrrrrrrrr.....#
#rrrrrrrrrrrrrrrrrr#
#rrrrrrrrFrrrrrrrrr#
#rrrrrrrrrrrrrrrrrr#
#....rrrrrrrrr###..#
#.....rrrrrrr.###..#
#...1..rrrrr..###..#
#.#.....rrr...2....#
#.##....rrr........#
#rrL....rrr.....Lrr#
#rrr....rrr.....rrr#
#rrr....rrr.....rrr#
##......rrr.......##
"""
