# 広場チャンク
# 中央に焚き火、周囲にランタンを配置

[[chunk]]
  name     = "50x20_town_plaza"
  palettes = ["standard", "town"]
  weight   = 1

  map = """
##..........rrr........rrr........rrr...........##
#rrr........rrr........rrr........rrr.........rrr#
#rrr........rrr........rrr........rrr.........rrr#
#rrL........rrr........rrr........rrr.........Lrr#
#...........rrr........rrr........rrr............#
#..$........rrrrr.....rrrrr.....rrrrr............#
#..........rrrrrrr...rrrrrrr...rrrrrrr........3..#
#.........rrrrrrrrr.rrrrrrrrr.rrrrrrrrr..........#
#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#
#rrrrrrrrrrFrrrrrrrrrrrrFrrrrrrrrrrrrFrrrrrrrrrrr#
#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#
#.........rrrrrrrrr.rrrrrrrrr.rrrrrrrrr..........#
#..........rrrrrrr...rrrrrrr...rrrrrrr...........#
#...1.......rrrrr.....rrrrr.....rrrrr............#
#...........rrr...2....rrr.......rrr.............#
#..##.......rrr........rrr.......rrr.............#
#rrL........rrr........rrr........rrr.........Lrr#
#rrr........rrr........rrr........rrr.........rrr#
#rrr........rrr........>rr........rrr.........rrr#
##..........rrr........rrr........rrr...........##
"""

  # プレイヤーの開始位置（広場の中央）
  [[chunk.spawn_points]]
    x = 24
    y = 10
