[[entity]]

  [entity.components.Text]
    color     = [255, 255, 255, 255]
    font_face = {font = "kappa", options.size = 25.0}
    id        = "level"
    text      = "1F"

  [entity.components.UITransform]
    origin      = "TopLeft"
    pivot       = "Dot"
    translation = {x = 10, y = -68}
