# 上部橋facility: 橋A, B, C（次フロアへの出口）

[[chunk]]
  map = """
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
"""
  name = "50x28_dungeon_bridge_top"
  palettes = ["standard"]
  weight = 1

  # 出口橋（左側）- 中央1マスのみ
  [[chunk.bridges]]
    bridge_id = "exit_left"
    x         = 2
    y         = 14

  # 出口橋（中央）- 中央1マスのみ
  [[chunk.bridges]]
    bridge_id = "exit_center"
    x         = 16
    y         = 14

  # 出口橋（右側）- 中央1マスのみ
  [[chunk.bridges]]
    bridge_id = "exit_right"
    x         = 30
    y         = 14
