# 上部橋facility: 橋A, B, C（次フロアへの出口）

[[chunk]]
  map = """
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
-...------------...------------...----------------
"""
  name = "50x28_dungeon_bridge_top"
  palettes = ["standard"]
  weight = 1

  # 橋A
  [[chunk.bridges]]
    bridge_id = "A"
    x         = 1
    y         = 14
  [[chunk.bridges]]
    bridge_id = "A"
    x         = 2
    y         = 14
  [[chunk.bridges]]
    bridge_id = "A"
    x         = 3
    y         = 14

  # 橋B
  [[chunk.bridges]]
    bridge_id = "B"
    x         = 16
    y         = 14
  [[chunk.bridges]]
    bridge_id = "B"
    x         = 17
    y         = 14
  [[chunk.bridges]]
    bridge_id = "B"
    x         = 18
    y         = 14

  # 橋C
  [[chunk.bridges]]
    bridge_id = "C"
    x         = 31
    y         = 14
  [[chunk.bridges]]
    bridge_id = "C"
    x         = 32
    y         = 14
  [[chunk.bridges]]
    bridge_id = "C"
    x         = 33
    y         = 14
