# 下部橋facility: 橋D（前フロアからの入口）

[[chunk]]
  map = """
------------------------I.I-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------I.I-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------I.I-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------I.I-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------...-----------------------
------------------------I.I-----------------------
"""
  name = "50x28_dungeon_bridge_bottom"
  palettes = ["standard"]
  weight = 1

  # 橋D
  [[chunk.bridges]]
    bridge_id = "D"
    x         = 25
    y         = 14
