# 上部橋facility: 橋A, B, C（次フロアへの出口）

[[chunk]]
  map = """
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
"""
  name = "50x28_dungeon_bridge_top"
  palettes = ["standard"]
  weight = 1

  # 橋A - 中央1マスのみ
  [[chunk.bridges]]
    bridge_id = "A"
    x         = 2
    y         = 14

  # 橋B - 中央1マスのみ
  [[chunk.bridges]]
    bridge_id = "B"
    x         = 16
    y         = 14

  # 橋C - 中央1マスのみ
  [[chunk.bridges]]
    bridge_id = "C"
    x         = 30
    y         = 14
