# 上部橋facility: 橋A, B, C（次フロアへの出口）

[[chunk]]
  map = """
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-...-----------...-----------...------------------
-I.I-----------I.I-----------I.I------------------
-.............-...-.............------------------
-.............-...-.............------------------
-----------I.I-I.I-I.I----------------------------
..................................................
"""
  name = "50x28_dungeon_bridge_top"
  palettes = ["standard"]
  weight = 1

  # スポーン地点(出)
  [[chunk.exits]]
    exit_id = "exit_left"
    x       = 2
    y       = 14

  # スポーン地点(出)
  [[chunk.exits]]
    exit_id = "exit_center"
    x       = 16
    y       = 14

  # スポーン地点(出)
  [[chunk.exits]]
    exit_id = "exit_right"
    x       = 30
    y       = 14

  # 橋のヒント表示位置
  [[chunk.bridge_hints]]
    exit_id = "exit_left"
    x       = 12
    y       = 26

  [[chunk.bridge_hints]]
    exit_id = "exit_center"
    x       = 16
    y       = 26

  [[chunk.bridge_hints]]
    exit_id = "exit_right"
    x       = 20
    y       = 26
