# 下部橋facility (幅20用): 橋D（前フロアからの入口）

[[chunk]]
  map = """
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
"""
  name = "20x28_town_bridge_bottom"
  palettes = ["standard"]
  weight = 1

  # 橋D
  [[chunk.bridges]]
    bridge_id = "D"
    x         = 10
    y         = 14
