# 上部橋facility (幅20用): 橋A（次フロアへの出口）

[[chunk]]
  map = """
--------I.I---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------I.I---------
--------...---------
--------...---------
--------...---------
--------I.I---------
--------...---------
--------...---------
--------...---------
--------I.I---------
--------...---------
--------...---------
--------...---------
--------I.I---------
"""
  name = "20x28_town_bridge_top"
  palettes = ["standard"]
  weight = 1

  # 出口橋 - 中央1マスのみ
  [[chunk.bridges]]
    bridge_id = "exit"
    x         = 9
    y         = 14
