# 上部橋facility (幅20用): 橋A（次フロアへの出口）

[[chunk]]
  map = """
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
"""
  name = "20x28_town_bridge_top"
  palettes = ["standard"]
  weight = 1

  # 橋A
  [[chunk.bridges]]
    bridge_id = "A"
    x         = 8
    y         = 14
  [[chunk.bridges]]
    bridge_id = "A"
    x         = 9
    y         = 14
  [[chunk.bridges]]
    bridge_id = "A"
    x         = 10
    y         = 14
