# 下部橋facility (幅20用): 橋D（前フロアからの入口）

[[chunk]]
  map = """
--------I.I---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------...---------
--------I.I---------
--------...---------
--------...---------
--------...---------
--------I.I---------
--------...---------
--------...---------
--------...---------
--------I.I---------
--------...---------
--------...---------
--------...---------
--------I.I---------
"""
  name = "20x28_town_bridge_bottom"
  palettes = ["standard"]
  weight = 1

  # スポーン地点(入)
  [[chunk.spawn_points]]
    x = 9
    y = 4
