# 街用パレット

[palette]
  description = "街用の地形パレット"
  id          = "town"

  # 地形の定義
  [palette.terrain]
    "." = "Dirt"  # 土
    "$" = "Dirt"  # 商人の下は土
    "1" = "Dirt"  # 老兵の下は土
    "2" = "Dirt"  # 怪しい科学者の下は土
    "3" = "Dirt"  # 闇医者の下は土
    "r" = "Floor" # 道路

  # NPCの定義
  [palette.npcs]
    "$" = "商人"
    "1" = "老兵"
    "2" = "怪しい科学者"
    "3" = "闇医者"
