# 街用パレット

[palette]
  description = "街用の地形パレット"
  id          = "town"

  # 地形の定義
  [palette.terrain]
    "." = "dirt"  # 土
    "$" = "dirt"  # 商人の下は土
    "1" = "dirt"  # 老兵の下は土
    "2" = "dirt"  # 怪しい科学者の下は土
    "3" = "dirt"  # 闇医者の下は土
    ">" = "dirt"  # 次階層ポータルの下は土
    "r" = "floor" # 道路

  # NPCの定義
  [palette.npcs]
    "$" = "商人"
    "1" = "老兵"
    "2" = "怪しい科学者"
    "3" = "闇医者"

  # Propsの定義
  [palette.props]
    ">" = "warp_next" # ダンジョン入口ポータル
